spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/example
    username: example
    password: example_pass
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true

kafka:
  servers: localhost:9092
  group.id: kafkaExampleConsumer
  max.poll:
    interval.ms: 10000
    records.count: 10
  topics:
    inbound: exampleInTopic

---
spring:
  main.banner-mode: "off"
  profiles: production
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

kafka:
  servers: ${KAFKA_SERVERS}
  group.id: ${KAFKA_GROUP_ID}
  max.poll:
    interval.ms: ${KAFKA_MAX_POLL_INTERVAL_MS}
    records.count: ${KAFKA_MAX_POLL_RECORS_COUNT}
  topics:
    inbound: ${KAFKA_INBOUND_TOPIC}
